image: node:15.4

stages:
  - test
  - deploy

test:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    - npm install -g typescript
    - npm install
    - npm run test
    - npm run compile

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    - npm install -g typescript
    - npm install
    - GITLAB_AUTH_TOKEN=$CI_JOB_TOKEN npm publish
